### ISSUE TITLE
wget http://downloads.sourceforge.net/libxls/libxls-0.2.0.tar.gz  404

### ISSUE THREAD

**Issue by Vano2903** [northbright/xls2csv-go#1]
Looks like the way you are downloading that tar is not available anymore.

**Comment by northbright** [comment]
[libxls](https://github.com/libxls/libxls/) hosted on Github now.
You may download [latest release](https://github.com/libxls/libxls/releases/tag/v1.6.2) on Github.
```
wget https://github.com/libxls/libxls/releases/download/v1.6.2/libxls-1.6.2.tar.gz
```
